function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Apr-2014 06:30:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[1 546]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 0.05]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'Marker','o','LineStyle','none');
set(plot1(1),'Color',[1 0 0],'DisplayName','ventriculos');
set(plot1(2),'Color',[0 0 1],'DisplayName','caudado');
set(plot1(3),'Color',[0 1 0],'DisplayName','hipocampo');

% Create xlabel
xlabel({'Fatias'});

% Create ylabel
ylabel({'DEP'});

% Create title
title({'Caso #1 - Medico #2'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.777842559959777 0.710220521095225 0.117884233273869 0.186654908877131]);

